#1.1.4配置已经迁移到apollo，以下配置为模板
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}
logging:
  level:
    com:
      platon:
        browser:
          task: debug
    org:
      springframework: error
mybatis:
  mapper-locations: classpath*:mapper/*.xml,classpath*:custommapper/*.xml
  type-aliases-package: com.platon.browser.dao.entity
platon:
  addIssueRate: 0.05
  addressPrefix: atp
  chainId: 201018
  defaultStakingLockedAmount: 10500
  electionBackwardBlockCount: 20
  es-namespace: browser_${profile}
  foundationSubsidies:
    '1': 0
    '2': 0
    '3': 0
    '4': 0
    '5': 0
    '6': 0
    '7': 0
    '8': 0
    '9': 0
  incentiveRateFromIssue: 0.4
  initIssueAmount: 100000000
  keyBase: https://keybase.io/
  keyBaseApi: _/api/1.0/user/lookup.json?key_suffix=
  maxBlockGasLimit: 201600000
  maxSettlePeriodCount4AnnualizedRateStat: 4
  paging:
    erc20-transaction:
      pageCount: 250
      pageSize: 2000
  proposalPipNumTemplate: AIP-%s
  proposalUrlTemplate: https://github.com/AlayaNetwork/AIPs/tree/master/Alaya/AIP-%s.md
  txLogDecodeThreadNum: 200
  valueUnit: ATP
  web3j:
    addresses: 192.168.112.141:7789,192.168.112.141:7790
    protocol: WS
profile: alaya
spring:
  application:
    name: scan-job
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ENC(bpshgjWOgn2d+oGmSTBPNA==)
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.9.191:3306/alaya_browser_hrpatp201018v10000?useUnicode=true&characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: ENC(bpshgjWOgn2d+oGmSTBPNA==)
  elasticsearch:
    high-level-client:
      hosts: 192.168.120.103,192.168.120.104,192.168.120.105
      password: changeme
      port: 9200
      schema: http
      username: elastic
    index:
      blockIndexName: ${platon.es-namespace}_block
      delegationIndexName: ${platon.es-namespace}_delegation
      delegationRewardIndexName: ${platon.es-namespace}_delegation_reward
      erc20TxIndexName: ${platon.es-namespace}_erc20_tx
      erc721TxIndexName: ${platon.es-namespace}_erc721_tx
      nodeOptIndexName: ${platon.es-namespace}_nodeopt
      transactionIndexName: ${platon.es-namespace}_transaction
      transferTxIndexName: ${platon.es-namespace}_transfer_tx
task:
  maxAddressCount: 5004
  maxBatchSize: 100
xxl:
  job:
    accessToken: GOJ4hui834hGIhHIh33984dG3DER4Gh784u9dh
    admin:
      addresses: http://192.168.120.144:18080/xxl-job-admin
    executor:
      appname: scan-job
      logpath: ./logs/jobhandler
      logretentiondays: 90
      port: 9997
