# ***************************开发配置**************************** #
# 当前激活的配置名称(请不要修改)
profile: prod
# 密码加密配置
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}
#Spring框架内部配置
spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://192.168.9.191:3306/platon_browser_hrplat100v10000?useSSL=false&useTimezone=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: platon
    password: platon

#日志配置
logging:
  #日志级别
  level:
    org.springframework: error
    org.springframework.retry: error
    com.platon.browser: error
    com.platon.browser.bootstrap: error
    com.platon.browser.collection: error
    com.platon.browser.collection.queue.handler: error
    com.platon.browser.common: error
    com.platon.browser.complement: error
    com.platon.browser.complement.handler: error
    com.platon.browser.complement.converter: error
    com.platon.browser.persistence: error
    com.platon.browser.persistence.handler: error
    com.platon.browser.persistence.queue.handler: error
    com.platon.browser.task: error
  file:
    name: ./logs/${spring.application.name}-${version}-${profile}.log
#PlatOn相关配置
platon:
  # 地址HRP前缀
  addressPrefix: lat
  # 金额显示单位
  valueUnit: LAT
  # 交易输入参数并行解码线程数
  txLogDecodeThreadNum: 200
  # Web3j访问地址
  web3j:
    #HTTP或WS
    protocol: HTTP
    addresses: 192.168.120.151:6789,192.168.120.151:6790
  #链id
  chainId: 100

task:
  #查询总记录数
  addressLimit: 5000
  #批量查询锁仓合约大小
  queryBatchSize: 2
  #基金会地址统计cron表达式
  fundAddressCron: 0/5  * * * * ?
  #内置合约地址统计cron表达式
  innerContractCron: 0/10  * * * * ?
