# ***************************通用配置: 请不要修改此文件，此文件由模板自动生成，若要修改，请移步至conftpl目录**************************** #
# 应用版本
version: 1.1.4
spring:
  application.name: scan-job
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  #ES索引配置
  elasticsearch:
    index:
      blockIndexName: ${platon.es-namespace}_block
      transactionIndexName: ${platon.es-namespace}_transaction
      delegationIndexName: ${platon.es-namespace}_delegation
      nodeOptIndexName: ${platon.es-namespace}_nodeopt
      delegationRewardIndexName: ${platon.es-namespace}_delegation_reward
      transferTxIndexName: ${platon.es-namespace}_transfer_tx
      erc20TxIndexName: ${platon.es-namespace}_erc20_tx
      erc721TxIndexName: ${platon.es-namespace}_erc721_tx
# MyBatis配置（注意：一定要对应mapper映射xml文件的所在路径）
mybatis:
  mapper-locations: classpath*:mapper/*.xml,classpath*:custommapper/*.xml
  # 实体类别名配置（注意：对应实体类的路径）
  type-aliases-package: com.platon.browser.dao.entity
#PlatOn相关配置
platon:
  addressPrefix: lat